// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHxggqzZlfOYrDoH37noa-F5paEvNlnwQ',
    appId: '1:573754594747:web:871a2b8854dc467e9d609e',
    messagingSenderId: '573754594747',
    projectId: 'rescuemed-90b7c',
    authDomain: 'rescuemed-90b7c.firebaseapp.com',
    storageBucket: 'rescuemed-90b7c.appspot.com',
    measurementId: 'G-CXCCNRYWTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjIPpzbNXjML85m7zoLeVID4wA_38FJM',
    appId: '1:573754594747:android:9affb94288bba1ce9d609e',
    messagingSenderId: '573754594747',
    projectId: 'rescuemed-90b7c',
    storageBucket: 'rescuemed-90b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOiOCRwauXFqG5cOsQO-hVnLBo9nah2k',
    appId: '1:573754594747:ios:41b52fabd4d5c93c9d609e',
    messagingSenderId: '573754594747',
    projectId: 'rescuemed-90b7c',
    storageBucket: 'rescuemed-90b7c.appspot.com',
    iosBundleId: 'com.example.rescueMedAmbulance',
  );

}